# ESP32 Hardware PWM Component for Sming Framework

COMPONENT_SRCDIRS := src
COMPONENT_INCDIRS := src/include

# ESP32 specific component - currently keeps esp8266 from building -
COMPONENT_SOC := esp32*

# Required for C++ features
# COMPONENT_CXXFLAGS += -std=c++17

# Add any specific compiler flags
ifdef ENABLE_DEBUG
    COMPONENT_CXXFLAGS += -DDEBUG_ESP_PWM
endif

# ---------------------------------------------------------------------------
# SOC-specific calibration table (generated by TimingTest_HwPWM)
#
# If src/calibration/HwPwmCalib_<SMING_SOC>.h exists the library compiles
# it in and auto-installs the table via a static initialiser — no changes
# needed in application code.
#
# To generate the file:
#   1. Build and flash TimingTest_HwPWM (no calibration file present yet)
#   2. Open serial monitor and capture the block between
#      "---- copy from here ----" and "---- copy to here ----"
#   3. Save it as  src/calibration/HwPwmCalib_$(SMING_SOC).h
#   4. Rebuild (this rule will detect it automatically)
#   5. Re-run TimingTest_HwPWM to validate the corrections
# ---------------------------------------------------------------------------
HWPWM_CALIB_HDR := $(COMPONENT_PATH)/src/calibration/HwPwmCalib_$(SMING_SOC).h
ifneq ($(wildcard $(HWPWM_CALIB_HDR)),)
  COMPONENT_CXXFLAGS += -DHWPWM_HAS_SOC_CALIB
  COMPONENT_CXXFLAGS += -DHWPWM_SOC_CALIB_HEADER='"HwPwmCalib_$(SMING_SOC).h"'
  COMPONENT_INCDIRS  += src/calibration
  $(info Esp32HardwarePwm: using SOC calibration table $(HWPWM_CALIB_HDR))
endif


