// HwPwmCalib_esp32.h
// Auto-generated by TimingTest_HwPWM — do not edit manually.
// Re-run TimingTest_HwPWM to regenerate.
//
// Copy to: Esp32HardwarePwm/src/calibration/HwPwmCalib_esp32.h
// and rebuild. The library detects and applies this table automatically.

#pragma once
#ifndef HWPWM_CALIB_esp32_H
#define HWPWM_CALIB_esp32_H

// clang-format off
static const Esp32HardwarePwm::CalibrationEntry hwpwmCalib_esp32[] = {
    // { frequency, resolution, overheadUs }
    {  1000, LEDC_TIMER_8_BIT,  1952 }, //  1kHz/ 8-bit
    { 15000, LEDC_TIMER_8_BIT,  1449 }, // 15kHz/ 8-bit
    { 16000, LEDC_TIMER_8_BIT,  1480 }, // 16kHz/ 8-bit
    {  1000, LEDC_TIMER_9_BIT,  6219 }, //  1kHz/ 9-bit
    {  2000, LEDC_TIMER_9_BIT,  1459 }, //  2kHz/ 9-bit
    {  1000, LEDC_TIMER_10_BIT,  2951 }, //  1kHz/10-bit
    {  2000, LEDC_TIMER_10_BIT,  1459 }, //  2kHz/10-bit
    {  3000, LEDC_TIMER_10_BIT,  1677 }, //  3kHz/10-bit
    {  4000, LEDC_TIMER_10_BIT,  1021 }, //  4kHz/10-bit
    {  5000, LEDC_TIMER_10_BIT,  1082 }, //  5kHz/10-bit
    {  1000, LEDC_TIMER_11_BIT,  2951 }, //  1kHz/11-bit
    {  2000, LEDC_TIMER_11_BIT,  1459 }, //  2kHz/11-bit
    {  3000, LEDC_TIMER_11_BIT,  1289 }, //  3kHz/11-bit
    {  4000, LEDC_TIMER_11_BIT,  1020 }, //  4kHz/11-bit
    {  5000, LEDC_TIMER_11_BIT,  1097 }, //  5kHz/11-bit
    {  6000, LEDC_TIMER_11_BIT,   298 }, //  6kHz/11-bit
    {  7000, LEDC_TIMER_11_BIT,   640 }, //  7kHz/11-bit
    {  8000, LEDC_TIMER_11_BIT,   724 }, //  8kHz/11-bit
    {  9000, LEDC_TIMER_11_BIT,  1450 }, //  9kHz/11-bit
    { 10000, LEDC_TIMER_11_BIT,  1143 }, // 10kHz/11-bit
    {  1000, LEDC_TIMER_12_BIT,  2951 }, //  1kHz/12-bit
    {  2000, LEDC_TIMER_12_BIT,  1459 }, //  2kHz/12-bit
    {  3000, LEDC_TIMER_12_BIT,   629 }, //  3kHz/12-bit
    {  4000, LEDC_TIMER_12_BIT,   958 }, //  4kHz/12-bit
    {  5000, LEDC_TIMER_12_BIT,   418 }, //  5kHz/12-bit
    {  6000, LEDC_TIMER_12_BIT,   729 }, //  6kHz/12-bit
    {  7000, LEDC_TIMER_12_BIT,   626 }, //  7kHz/12-bit
    {  8000, LEDC_TIMER_12_BIT,   724 }, //  8kHz/12-bit
    {  9000, LEDC_TIMER_12_BIT,   336 }, //  9kHz/12-bit
    { 10000, LEDC_TIMER_12_BIT,   738 }, // 10kHz/12-bit
    { 11000, LEDC_TIMER_12_BIT,   797 }, // 11kHz/12-bit
    { 12000, LEDC_TIMER_12_BIT,   145 }, // 12kHz/12-bit
    { 13000, LEDC_TIMER_12_BIT,   734 }, // 13kHz/12-bit
    { 14000, LEDC_TIMER_12_BIT,   444 }, // 14kHz/12-bit
    { 15000, LEDC_TIMER_12_BIT,   382 }, // 15kHz/12-bit
    { 16000, LEDC_TIMER_12_BIT,   566 }, // 16kHz/12-bit
    {  1000, LEDC_TIMER_13_BIT,  2923 }, //  1kHz/13-bit
    {  2000, LEDC_TIMER_13_BIT,  1459 }, //  2kHz/13-bit
    {  3000, LEDC_TIMER_13_BIT,   950 }, //  3kHz/13-bit
    {  4000, LEDC_TIMER_13_BIT,   709 }, //  4kHz/13-bit
    {  5000, LEDC_TIMER_13_BIT,   558 }, //  5kHz/13-bit
    {  6000, LEDC_TIMER_13_BIT,   310 }, //  6kHz/13-bit
    {  7000, LEDC_TIMER_13_BIT,   433 }, //  7kHz/13-bit
    {  8000, LEDC_TIMER_13_BIT,   240 }, //  8kHz/13-bit
    {  9000, LEDC_TIMER_13_BIT,   335 }, //  9kHz/13-bit
    {  1000, LEDC_TIMER_14_BIT,  2920 }, //  1kHz/14-bit
    {  2000, LEDC_TIMER_14_BIT,  1426 }, //  2kHz/14-bit
    {  3000, LEDC_TIMER_14_BIT,   609 }, //  3kHz/14-bit
    {  4000, LEDC_TIMER_14_BIT,   518 }, //  4kHz/14-bit
};
// clang-format on

#define HWPWM_CALIB_TABLE hwpwmCalib_esp32
#define HWPWM_CALIB_COUNT (sizeof(hwpwmCalib_esp32) / sizeof(hwpwmCalib_esp32[0]))

#endif // HWPWM_CALIB_esp32_H
