// HwPwmCalib_esp32.h
// Auto-generated by TimingTest_HwPWM — do not edit manually.
// Re-run TimingTest_HwPWM to regenerate.
//
// Copy to: Esp32HardwarePwm/src/calibration/HwPwmCalib_esp32.h
// and rebuild. The library detects and applies this table automatically.

#pragma once
#ifndef HWPWM_CALIB_esp32_H
#define HWPWM_CALIB_esp32_H

// clang-format off
// Entries only exist where IDF scale >= 10 (large scale, linear response to
// requested-time adjustments).  Small-scale (2–9) configs are excluded because
// a 1 ms shift in the carry-adjusted request changes IDF scale by ±1, which
// moves the actual LEDC duration by 2–5 ms — making calibration oscillate.
// Those configs fall back to the formula in computeReloadOverhead().
static const Esp32HardwarePwm::CalibrationEntry hwpwmCalib_esp32[] = {
    // { frequency, resolution, overheadUs }
    // ---- 8-bit: only 1 kHz has scale >= 10 (scale=14); 15/16 kHz use cycle_num path ----
    {  1000, LEDC_TIMER_8_BIT,  1953 }, //  1kHz/ 8-bit  scale=14
    { 15000, LEDC_TIMER_8_BIT,  1449 }, // 15kHz/ 8-bit  cycle_num path
    { 16000, LEDC_TIMER_8_BIT,  1481 }, // 16kHz/ 8-bit  cycle_num path
    // ---- 9-bit: 1–2 kHz only (scale 28, 14) ----
    {  1000, LEDC_TIMER_9_BIT,  6267 }, //  1kHz/ 9-bit  scale=28
    {  2000, LEDC_TIMER_9_BIT,  1459 }, //  2kHz/ 9-bit  scale=14
    // ---- 10-bit: 1–5 kHz (scale 56, 28, 17, 13, 10) ----
    {  1000, LEDC_TIMER_10_BIT,  2952 }, //  1kHz/10-bit  scale=56
    {  2000, LEDC_TIMER_10_BIT,  1459 }, //  2kHz/10-bit  scale=28
    {  3000, LEDC_TIMER_10_BIT,  1678 }, //  3kHz/10-bit  scale=17
    {  4000, LEDC_TIMER_10_BIT,  1022 }, //  4kHz/10-bit  scale=13
    {  5000, LEDC_TIMER_10_BIT,  1083 }, //  5kHz/10-bit  scale=10
    // ---- 11-bit: 1–10 kHz (scale 113..10) ----
    {  1000, LEDC_TIMER_11_BIT,  2952 }, //  1kHz/11-bit  scale=113
    {  2000, LEDC_TIMER_11_BIT,  1460 }, //  2kHz/11-bit  scale=56
    {  3000, LEDC_TIMER_11_BIT,  1290 }, //  3kHz/11-bit  scale=35
    {  4000, LEDC_TIMER_11_BIT,  1021 }, //  4kHz/11-bit  scale=26
    {  5000, LEDC_TIMER_11_BIT,  1098 }, //  5kHz/11-bit  scale=21
    {  6000, LEDC_TIMER_11_BIT,   299 }, //  6kHz/11-bit  scale=17
    {  7000, LEDC_TIMER_11_BIT,   640 }, //  7kHz/11-bit  scale=15
    {  8000, LEDC_TIMER_11_BIT,   725 }, //  8kHz/11-bit  scale=13
    {  9000, LEDC_TIMER_11_BIT,  1451 }, //  9kHz/11-bit  scale=11
    { 10000, LEDC_TIMER_11_BIT,  1144 }, // 10kHz/11-bit  scale=10
    {  1000, LEDC_TIMER_12_BIT,  2952 }, //  1kHz/12-bit
    {  2000, LEDC_TIMER_12_BIT,  1460 }, //  2kHz/12-bit
    {  3000, LEDC_TIMER_12_BIT,   630 }, //  3kHz/12-bit
    {  4000, LEDC_TIMER_12_BIT,   959 }, //  4kHz/12-bit
    {  5000, LEDC_TIMER_12_BIT,   419 }, //  5kHz/12-bit
    {  6000, LEDC_TIMER_12_BIT,   730 }, //  6kHz/12-bit
    {  7000, LEDC_TIMER_12_BIT,   627 }, //  7kHz/12-bit
    {  8000, LEDC_TIMER_12_BIT,   725 }, //  8kHz/12-bit
    {  9000, LEDC_TIMER_12_BIT,   337 }, //  9kHz/12-bit
    { 10000, LEDC_TIMER_12_BIT,   739 }, // 10kHz/12-bit
    { 11000, LEDC_TIMER_12_BIT,   798 }, // 11kHz/12-bit
    { 12000, LEDC_TIMER_12_BIT,   146 }, // 12kHz/12-bit
    { 13000, LEDC_TIMER_12_BIT,   735 }, // 13kHz/12-bit
    { 14000, LEDC_TIMER_12_BIT,   445 }, // 14kHz/12-bit
    { 15000, LEDC_TIMER_12_BIT,   383 }, // 15kHz/12-bit
    { 16000, LEDC_TIMER_12_BIT,   566 }, // 16kHz/12-bit
    {  1000, LEDC_TIMER_13_BIT,  2921 }, //  1kHz/13-bit
    {  2000, LEDC_TIMER_13_BIT,  1460 }, //  2kHz/13-bit
    {  3000, LEDC_TIMER_13_BIT,   951 }, //  3kHz/13-bit
    {  4000, LEDC_TIMER_13_BIT,   710 }, //  4kHz/13-bit
    {  5000, LEDC_TIMER_13_BIT,   559 }, //  5kHz/13-bit
    {  6000, LEDC_TIMER_13_BIT,   311 }, //  6kHz/13-bit
    {  7000, LEDC_TIMER_13_BIT,   434 }, //  7kHz/13-bit
    {  8000, LEDC_TIMER_13_BIT,   241 }, //  8kHz/13-bit
    {  9000, LEDC_TIMER_13_BIT,   336 }, //  9kHz/13-bit
    {  1000, LEDC_TIMER_14_BIT,  2921 }, //  1kHz/14-bit
    {  2000, LEDC_TIMER_14_BIT,  1427 }, //  2kHz/14-bit
    {  3000, LEDC_TIMER_14_BIT,   610 }, //  3kHz/14-bit
    {  4000, LEDC_TIMER_14_BIT,   520 }, //  4kHz/14-bit
};
// clang-format on

#define HWPWM_CALIB_TABLE hwpwmCalib_esp32
#define HWPWM_CALIB_COUNT (sizeof(hwpwmCalib_esp32)/sizeof(hwpwmCalib_esp32[0]))

#endif // HWPWM_CALIB_esp32_H

